name: publish
on: [push]
jobs:
publish-hello-docker-image:
- name: publish docker image
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Build the hello-docker Docker image
run: npm install express
