name: publish
on: [push]
jobs:
publish-hello-docker-image:
- name: publish docker image
runs-on: ubuntu-latest

steps:
- uses: actions/checkout@v2

- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{github.actor}}
password: ${{secrets.GITHUB_TOKEN}}

- name: Build the hello-docker Docker image
run: |
       docker build . --tag ghcr.io/gkaranth/hello-docker-gcr-demo:latest
       docker run ghcr.io/gkaranth/hello-docker-gcr-demo:latest
       docker push ghcr.io/gkaranth/hello-docker-gcr-demo:latest